create database grocery_store_management;
use grocery_store_management;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

desc supplier;

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

desc categories;

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

desc employees;

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

desc customers;

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

desc products;

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

desc orders;

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

desc order_details;

SELECT * FROM categories;
SELECT * FROM supplier;
SELECT * FROM employees;
SELECT * FROM products; 
SELECT * FROM customers; 
SELECT * FROM orders; 
SELECT * FROM order_details; 

-- Analysis Questions 
-- 1 . Customer Insights 
-- Gain an understanding of customer engagement and purchasing behavior. 
-- ● How many unique customers have placed orders? 

select count(distinct cust_id) customers
from orders;

-- ● Which customers have placed the highest number of orders? 

select cust_id,count(ord_id) total_orders
from orders
group by cust_id
order by total_orders desc
limit 5;


-- ● What is the total and average purchase value per customer? 

select cust_id,sum(order_value) total_purchase, avg(order_value) avg_purchase
from (
select o.cust_id,o.ord_id,sum(d.total_price) order_value
from orders o
join order_details d
on o.ord_id=d.ord_id
group by o.cust_id,o.ord_id) as t
group by cust_id;

-- ● Who are the top 5 customers by total purchase amount? 

select o.cust_id,sum(d.total_price) total_purchase
from orders o
join order_details d
on o.ord_id=d.ord_id
group by o.cust_id
order by total_purchase desc
limit 5;

-- 2. Product Performance 
-- Evaluate how well products are performing in terms of sales and revenue. 
-- ● How many products exist in each category? 

select c.cat_name,
       count(*) as no_of_products
from products p
join categories c
on p.cat_id=c.cat_id
group by c.cat_name;

-- ● What is the average price of products by category? 

select c.cat_name,avg(p.price) avg_prod_price
from products p
join categories c
on c.cat_id=p.cat_id
group by cat_name;

-- ● Which products have the highest total sales volume (by quantity)? 

select p.prod_name, sum(o.quantity) total_quantity_sales
from products p
join order_details o
on o.prod_id=p.prod_id
group by prod_name
order by total_quantity_sales desc
limit 5;

-- ● What is the total revenue generated by each product? 

SELECT p.prod_id,
       p.prod_name,
       SUM(od.total_price) AS total_revenue
FROM products p
JOIN order_details od
ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name;

-- ● How do product sales vary by category and supplier? 

select c.cat_name,sup_name,sum(o.total_price) total_sales
from products p
join order_details o 
on o.prod_id=p.prod_id
join categories c
on c.cat_id=p.cat_id
join supplier s
on s.sup_id=p.sup_id
group by c.cat_name,sup_name;

-- 3. Sales and Order Trends 
-- Analyze business performance through orders and revenue over time. 
-- ● How many orders have been placed in total? 

select count(*)total_orders from orders;

-- ● What is the average value per order? 

select avg(order_value) avg_order_value
from (
select ord_id, sum(total_price) order_value
from order_details
group by ord_id) as t;

-- ● On which dates were the most orders placed? 

select order_date,count(*) orders_placed from orders
group by order_date
order by orders_placed desc
limit 2;


-- ● What are the monthly trends in order volume and revenue? 

SELECT MONTH(STR_TO_DATE(o.order_date,'%m/%d/%y')) AS month_no,
       COUNT(DISTINCT o.ord_id) AS total_orders,
       SUM(od.total_price) AS revenue
FROM orders o
JOIN order_details od
ON o.ord_id = od.ord_id
GROUP BY month_no
ORDER BY month_no;

-- ● How do order patterns vary across weekdays and weekends? 

select case 
when weekday(str_to_date(order_date,'%m/%d/%y')) in (5,6) then 'Weekend'
    else 'Weekday'
end as type_of_week,
count(distinct o.ord_id) total_orders ,sum(d.total_price) total_price
from orders o
join order_details d
on o.ord_id = d.ord_id
group by type_of_week;

-- 4 . Supplier Contribution 
-- Identify the most active and profitable suppliers. 
-- ● How many suppliers are there in the database? 
select count(*) total_suppliers from supplier;
 
-- ● Which supplier provides the most products? 

select p.sup_id,s.sup_name, count(*) no_of_products
from products p
join supplier s
on p.sup_id=s.sup_id
group by p.sup_id
order by no_of_products desc;

-- ● What is the average price of products from each supplier? 

select p.sup_id,s.sup_name,avg(p.price)
from products p
join supplier s
on p.sup_id=s.sup_id
group by p.sup_id;

-- ● Which suppliers contribute the most to total product sales (by revenue)? 

select p.sup_id,s.sup_name,sum(o.total_price) total_price
from products p
join supplier s
on p.sup_id=s.sup_id
join order_details o
on p.prod_id=o.prod_id
group by p.sup_id
order by total_price desc;


-- 5 . Employee Performance 
-- Assess how employees are handling and influencing sales. 
-- ● How many employees have processed orders? 

select count(distinct emp_id) from orders;

-- ● Which employees have handled the most orders? 

select e.emp_name,count(*) orders 
from orders o
join employees e
on e.emp_id=o.emp_id
group by o.emp_id
order by orders desc;

-- ● What is the total sales value processed by each employee? 

select o.emp_id,sum(d.total_price) total_sales
from order_details d
join orders o
on o.ord_id=d.ord_id
group by o.emp_id;

-- ● What is the average order value handled per employee? 

select o.emp_id, avg(t.order_value) avg_order_value
from (select ord_id,sum(total_price) order_value from order_details
group by ord_id) as t
join orders o
ON t.ord_id = o.ord_id
group by o.emp_id;

-- 6 . Order Details Deep Dive 
-- Explore item-level sales patterns and pricing behavior.  
-- ● What is the relationship between quantity ordered and total price? 

SELECT quantity, avg(total_price)
FROM order_details
group by quantity
order by quantity;

-- ● What is the average quantity ordered per product? 

SELECT p.prod_id,p.prod_name, avg(o.quantity) avg_quantity
FROM order_details o
join products p
on p.prod_id=o.prod_id
group by prod_id
order by prod_id;

-- ● How does the unit price vary across products and orders?
SELECT
    p.prod_id,
    p.prod_name,
    AVG(od.total_price / od.quantity) AS avg_unit_price
FROM order_details od
JOIN products p
ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY avg_unit_price ;